/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.clinica.view;

import java.net.URL;

/**
 *
 * @author Jonathan
 */
public class GerenteUI extends javax.swing.JFrame {

    /**
     * Creates new form GerenteUI
     */
    
    private LoginUI l;
    private static CadastroPacienteUI p = new CadastroPacienteUI();
    private static CadastroAtendenteUI a = new CadastroAtendenteUI();
    private static CadastroMedicoUI m = new CadastroMedicoUI();
    private static CadastroGerenteUI g = new CadastroGerenteUI();
   
    URL url  = this.getClass().getResource("/com/clinica/images/gerente.png");
    
    public GerenteUI() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setIconImage(this.getToolkit().getImage(url));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        addpacienteMenu = new javax.swing.JMenuItem();
        addmedicoMenu = new javax.swing.JMenuItem();
        addatendenteMenu = new javax.swing.JMenuItem();
        menuAddGerente = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuAddSetor = new javax.swing.JMenuItem();
        addvalorCMenu = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        menuEditarAorG = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuEditarPaciente = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuEditarSetor = new javax.swing.JMenuItem();
        menuEditarValorConsulta = new javax.swing.JMenuItem();
        menuDeletarCadastros = new javax.swing.JMenu();
        menuDeletarPaciente = new javax.swing.JMenuItem();
        menuDeletarMedico = new javax.swing.JMenuItem();
        menuDeletarAtendente = new javax.swing.JMenuItem();
        menuDeletarGerente = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menuDeletarSetor = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        cpacienteMenu = new javax.swing.JMenuItem();
        cmedicoMenu = new javax.swing.JMenuItem();
        catendenteMenu = new javax.swing.JMenuItem();
        menuConsultasSetor = new javax.swing.JMenuItem();
        menuConsultasConsulta = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        cfolhapagamentoMenu = new javax.swing.JMenuItem();
        chistoricofrequenciaMenu = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        clistapacienteMenu = new javax.swing.JMenuItem();
        clistamedicoMenu = new javax.swing.JMenuItem();
        clistaatendenteMenu = new javax.swing.JMenuItem();
        menuListaConsulta = new javax.swing.JMenuItem();
        menuListaSetores = new javax.swing.JMenuItem();
        sairMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerente");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setName("gerenteFrame"); // NOI18N
        setUndecorated(true);
        setSize(new java.awt.Dimension(2147483647, 2147483647));

        backgroundPanel.setBackground(new java.awt.Color(51, 204, 255));

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 805, Short.MAX_VALUE)
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        menuCadastros.setBackground(new java.awt.Color(255, 255, 255));
        menuCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/cadastro.png"))); // NOI18N
        menuCadastros.setText("Cadastros");
        menuCadastros.setBorderPainted(false);
        menuCadastros.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N

        addpacienteMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        addpacienteMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addpacienteMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/pessoa.png"))); // NOI18N
        addpacienteMenu.setText("Cadastrar Paciente");
        addpacienteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpacienteMenuActionPerformed(evt);
            }
        });
        menuCadastros.add(addpacienteMenu);

        addmedicoMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        addmedicoMenu.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        addmedicoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/medico.png"))); // NOI18N
        addmedicoMenu.setText("Cadastrar Médico");
        addmedicoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmedicoMenuActionPerformed(evt);
            }
        });
        menuCadastros.add(addmedicoMenu);

        addatendenteMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        addatendenteMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addatendenteMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/atendente.png"))); // NOI18N
        addatendenteMenu.setText("Cadastrar Atendente");
        addatendenteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addatendenteMenuActionPerformed(evt);
            }
        });
        menuCadastros.add(addatendenteMenu);

        menuAddGerente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        menuAddGerente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuAddGerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/gerente.png"))); // NOI18N
        menuAddGerente.setText("Cadastrar Gerente");
        menuAddGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddGerenteActionPerformed(evt);
            }
        });
        menuCadastros.add(menuAddGerente);
        menuCadastros.add(jSeparator1);

        menuAddSetor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        menuAddSetor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuAddSetor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/5585Add_Folder_25911.png"))); // NOI18N
        menuAddSetor.setText("Cadastrar Setores");
        menuCadastros.add(menuAddSetor);

        addvalorCMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        addvalorCMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addvalorCMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/valorConsulta.png"))); // NOI18N
        addvalorCMenu.setText("Cadastrar Valor De Consulta");
        menuCadastros.add(addvalorCMenu);

        jMenuBar1.add(menuCadastros);

        menuEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/5298edit-document_icon-icons.com_54542.png"))); // NOI18N
        menuEditar.setText("Editar Cadastros");
        menuEditar.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N

        menuEditarAorG.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuEditarAorG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/8265businessapplication_edit_male_user_thepencil_theclient_negocio_2321.png"))); // NOI18N
        menuEditarAorG.setText("Editar Atendente/Gerente");
        menuEditar.add(menuEditarAorG);

        jMenuItem1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/medico.png"))); // NOI18N
        jMenuItem1.setText("Editar Médico");
        menuEditar.add(jMenuItem1);

        menuEditarPaciente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuEditarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/pessoa.png"))); // NOI18N
        menuEditarPaciente.setText("Editar Paciente");
        menuEditar.add(menuEditarPaciente);
        menuEditar.add(jSeparator4);

        menuEditarSetor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuEditarSetor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/5585Add_Folder_25911.png"))); // NOI18N
        menuEditarSetor.setText("Editar Setor");
        menuEditar.add(menuEditarSetor);

        menuEditarValorConsulta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuEditarValorConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/valorConsulta.png"))); // NOI18N
        menuEditarValorConsulta.setText("Editar Valor da Consulta");
        menuEditar.add(menuEditarValorConsulta);

        jMenuBar1.add(menuEditar);

        menuDeletarCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/flame_106452.png"))); // NOI18N
        menuDeletarCadastros.setText("Deletar Cadastros");
        menuDeletarCadastros.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N

        menuDeletarPaciente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuDeletarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/pessoa.png"))); // NOI18N
        menuDeletarPaciente.setText("Deletar Paciente");
        menuDeletarCadastros.add(menuDeletarPaciente);

        menuDeletarMedico.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuDeletarMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/medico.png"))); // NOI18N
        menuDeletarMedico.setText("Deletar Médico");
        menuDeletarCadastros.add(menuDeletarMedico);

        menuDeletarAtendente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuDeletarAtendente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/atendente.png"))); // NOI18N
        menuDeletarAtendente.setText("Deletar Atendente");
        menuDeletarCadastros.add(menuDeletarAtendente);

        menuDeletarGerente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuDeletarGerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/gerente.png"))); // NOI18N
        menuDeletarGerente.setText("Deletar Gerente");
        menuDeletarCadastros.add(menuDeletarGerente);
        menuDeletarCadastros.add(jSeparator5);

        menuDeletarSetor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuDeletarSetor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/5585Add_Folder_25911.png"))); // NOI18N
        menuDeletarSetor.setText("Deletar Setor");
        menuDeletarCadastros.add(menuDeletarSetor);

        jMenuItem2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/consulta.png"))); // NOI18N
        jMenuItem2.setText("Deletar Consulta");
        menuDeletarCadastros.add(jMenuItem2);

        jMenuBar1.add(menuDeletarCadastros);

        menuConsultas.setBackground(new java.awt.Color(255, 255, 255));
        menuConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/search.png"))); // NOI18N
        menuConsultas.setText("Consultas");
        menuConsultas.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N

        cpacienteMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        cpacienteMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cpacienteMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/pessoa.png"))); // NOI18N
        cpacienteMenu.setText("Paciente");
        menuConsultas.add(cpacienteMenu);

        cmedicoMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK));
        cmedicoMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmedicoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/medico.png"))); // NOI18N
        cmedicoMenu.setText("Médico");
        menuConsultas.add(cmedicoMenu);

        catendenteMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        catendenteMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        catendenteMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/atendente.png"))); // NOI18N
        catendenteMenu.setText("Atendente");
        menuConsultas.add(catendenteMenu);

        menuConsultasSetor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        menuConsultasSetor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuConsultasSetor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/5585Add_Folder_25911.png"))); // NOI18N
        menuConsultasSetor.setText("Setor");
        menuConsultas.add(menuConsultasSetor);

        menuConsultasConsulta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        menuConsultasConsulta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuConsultasConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/consulta.png"))); // NOI18N
        menuConsultasConsulta.setText("Consulta");
        menuConsultas.add(menuConsultasConsulta);
        menuConsultas.add(jSeparator2);

        cfolhapagamentoMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        cfolhapagamentoMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cfolhapagamentoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/folhaPagamento.png"))); // NOI18N
        cfolhapagamentoMenu.setText("Folha De Pagamento");
        menuConsultas.add(cfolhapagamentoMenu);

        chistoricofrequenciaMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        chistoricofrequenciaMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chistoricofrequenciaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/frequencia.png"))); // NOI18N
        chistoricofrequenciaMenu.setText("Histórico De Frequência");
        menuConsultas.add(chistoricofrequenciaMenu);
        menuConsultas.add(jSeparator3);

        clistapacienteMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        clistapacienteMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        clistapacienteMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/pessoa.png"))); // NOI18N
        clistapacienteMenu.setText("Lista De Pacientes");
        menuConsultas.add(clistapacienteMenu);

        clistamedicoMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        clistamedicoMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        clistamedicoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/medico.png"))); // NOI18N
        clistamedicoMenu.setText("Lista De Médicos");
        menuConsultas.add(clistamedicoMenu);

        clistaatendenteMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        clistaatendenteMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        clistaatendenteMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/atendente.png"))); // NOI18N
        clistaatendenteMenu.setText("Lista De Atendentes");
        menuConsultas.add(clistaatendenteMenu);

        menuListaConsulta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        menuListaConsulta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuListaConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/consulta.png"))); // NOI18N
        menuListaConsulta.setText("Lista De Consultas");
        menuConsultas.add(menuListaConsulta);

        menuListaSetores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        menuListaSetores.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuListaSetores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/5585Add_Folder_25911.png"))); // NOI18N
        menuListaSetores.setText("Lista de Setores");
        menuConsultas.add(menuListaSetores);

        jMenuBar1.add(menuConsultas);

        sairMenu.setBackground(new java.awt.Color(255, 255, 255));
        sairMenu.setForeground(new java.awt.Color(255, 51, 51));
        sairMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/signout.png"))); // NOI18N
        sairMenu.setText("Sair");
        sairMenu.setToolTipText("");
        sairMenu.setFocusPainted(true);
        sairMenu.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        sairMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sairMenuMouseEntered(evt);
            }
        });
        jMenuBar1.add(sairMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sairMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMenuMouseClicked
        
       l = new LoginUI();
       
       l.setVisible(true);
       this.dispose();
        
    }//GEN-LAST:event_sairMenuMouseClicked

    private void sairMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMenuMouseEntered
        sairMenu.setToolTipText("Aperte para sair");
    }//GEN-LAST:event_sairMenuMouseEntered

    private void addpacienteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpacienteMenuActionPerformed
        p.setVisible(true);
    }//GEN-LAST:event_addpacienteMenuActionPerformed

    private void addatendenteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addatendenteMenuActionPerformed
        a.setVisible(true);
    }//GEN-LAST:event_addatendenteMenuActionPerformed

    private void addmedicoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmedicoMenuActionPerformed
        m.setVisible(true);
    }//GEN-LAST:event_addmedicoMenuActionPerformed

    private void menuAddGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddGerenteActionPerformed
        g.setVisible(true);
    }//GEN-LAST:event_menuAddGerenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenteUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addatendenteMenu;
    private javax.swing.JMenuItem addmedicoMenu;
    private javax.swing.JMenuItem addpacienteMenu;
    private javax.swing.JMenuItem addvalorCMenu;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JMenuItem catendenteMenu;
    private javax.swing.JMenuItem cfolhapagamentoMenu;
    private javax.swing.JMenuItem chistoricofrequenciaMenu;
    private javax.swing.JMenuItem clistaatendenteMenu;
    private javax.swing.JMenuItem clistamedicoMenu;
    private javax.swing.JMenuItem clistapacienteMenu;
    private javax.swing.JMenuItem cmedicoMenu;
    private javax.swing.JMenuItem cpacienteMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuItem menuAddGerente;
    private javax.swing.JMenuItem menuAddSetor;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenuItem menuConsultasConsulta;
    private javax.swing.JMenuItem menuConsultasSetor;
    private javax.swing.JMenuItem menuDeletarAtendente;
    private javax.swing.JMenu menuDeletarCadastros;
    private javax.swing.JMenuItem menuDeletarGerente;
    private javax.swing.JMenuItem menuDeletarMedico;
    private javax.swing.JMenuItem menuDeletarPaciente;
    private javax.swing.JMenuItem menuDeletarSetor;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenuItem menuEditarAorG;
    private javax.swing.JMenuItem menuEditarPaciente;
    private javax.swing.JMenuItem menuEditarSetor;
    private javax.swing.JMenuItem menuEditarValorConsulta;
    private javax.swing.JMenuItem menuListaConsulta;
    private javax.swing.JMenuItem menuListaSetores;
    private javax.swing.JMenu sairMenu;
    // End of variables declaration//GEN-END:variables
}
